services:
  php-apache:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: php-api
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: S3cr3tDB!
      MYSQL_DATABASE: programming_languages
      MYSQL_USER: php_user
      MYSQL_PASSWORD: D8abase!
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql_data:

